name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types: [ "completed" ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH (git pull en el server)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd ~/lemp-sites/${{ secrets.REMOTE_FOLDER }}
            # Asegura que el repo está en main y hace pull
            git checkout main
            git pull --ff-only origin main
            echo "Commit en server:"
            git --no-pager log -1 --pretty=oneline
